version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django-web
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/ssl/certs:ro
      - static_volume:/app/staticfiles:ro
#      - certbot_data:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - static_volume:/app/staticfiles
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A online_store worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A online_store beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    build: .
    command: celery -A online_store flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
  static_volume:
  certbot_data:
