# Generated by Django 5.2 on 2026-07-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=100, verbose_name='نام الگو')),
                ('type', models.CharField(choices=[('otp', 'OTP')], max_length=50, unique=True, verbose_name='نوع الگو')),
                ('pattern_code', models.CharField(max_length=100, verbose_name='کد پترن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'الگوی پیامک',
                'verbose_name_plural': 'الگوهای پیامک',
            },
        ),
    ]
