# Generated by Django 5.2 on 2026-07-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspattern',
            name='type',
            field=models.CharField(choices=[('OTP', 'OTP'), ('new_repair_request', 'درخواست جدید تعمیر'), ('new_install_request', 'درخواست جدید نصب')], max_length=50, unique=True, verbose_name='نوع الگو'),
        ),
    ]
