# Generated by Django 5.2 on 2026-07-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_smspattern_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspattern',
            name='type',
            field=models.CharField(choices=[('OTP', 'OTP'), ('new_repair_request', 'درخواست جدید تعمیر'), ('new_install_request', 'درخواست جدید نصب'), ('repair_request_confirmation', 'تایید درخواست تعمیر'), ('install_request_confirmation', 'تایید درخواست نصب')], max_length=50, unique=True, verbose_name='نوع الگو'),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('pattern_type', models.CharField(max_length=50)),
                ('recipient', models.JSONField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('bulk_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pattern_type', 'status'], name='core_smslog_pattern_12187a_idx')],
            },
        ),
    ]
