# Generated by Django 5.2 on 2026-07-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_smspattern_type_smslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at'], 'verbose_name': '↧ لاگ ارسال پیامک', 'verbose_name_plural': '↧ لاگهای ارسال پیامک'},
        ),
    ]
