# Generated by Django 5.2 on 2026-10-01 20:32

from django.db import migrations, models


def seed_site_settings(apps, schema_editor):
    from decouple import config

    from core.models import parse_phone_numbers

    SiteSettings = apps.get_model('core', 'SiteSettings')
    db = schema_editor.connection.alias
    if SiteSettings.objects.using(db).exists():
        return

    api_key = str(config('MEDIANA_API_KEY', default='') or '').strip()
    from_number = str(config('MEDIANA_FROM_NUMBER', default='') or '').strip()
    if not api_key or not from_number:
        return

    SiteSettings.objects.using(db).create(
        admin_phone_numbers=','.join(parse_phone_numbers(config('ADMIN_PHONE_NUMBERS', default=''))),
        master_otp_code=str(config('MASTER_OTP_CODE', default='') or '').strip()[:8],
        mediana_base_url=str(config('MEDIANA_BASE_URL', default='https://edge.ippanel.com') or 'https://edge.ippanel.com').strip(),
        mediana_api_key=api_key,
        mediana_from_number=from_number,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_smslog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('admin_phone_numbers', models.TextField(blank=True, help_text='شماره\u200cها را با کاما جدا کنید. مثال: 09123456789,09351234567', verbose_name='شماره\u200cهای ادمین')),
                ('master_otp_code', models.CharField(blank=True, help_text='اگر پر شود، این کد به\u200cجای پیامک هم پذیرفته می\u200cشود. خالی یعنی غیرفعال.', max_length=8, verbose_name='کد OTP اصلی')),
                ('mediana_base_url', models.URLField(default='https://edge.ippanel.com', verbose_name='آدرس API مدیانا')),
                ('mediana_api_key', models.CharField(max_length=512, verbose_name='کلید API مدیانا')),
                ('mediana_from_number', models.CharField(max_length=32, verbose_name='شماره خط ارسال')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.RunPython(seed_site_settings, migrations.RunPython.noop),
    ]
