# Generated by Django 5.2 on 2026-06-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category-image', verbose_name='تصویر')),
                ('icon', models.FileField(blank=True, null=True, upload_to='category-icon', verbose_name='آیکن')),
                ('homepage_show', models.BooleanField(db_index=True, default=False, verbose_name='نمایش در صفحه اصلی')),
                ('order', models.IntegerField(db_index=True, default=10, verbose_name='ترتیب')),
                ('seo_keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='کلمات سرچ یا سئو')),
                ('seo_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات سئو')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product.category', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('main_price', models.BigIntegerField(verbose_name='قیمت اصلی')),
                ('sell_price', models.BigIntegerField(verbose_name='قیمت فروش')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_types', to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('image', models.ImageField(upload_to='product-images', verbose_name='تصویر')),
                ('is_thumbnail', models.BooleanField(db_index=True, default=False, verbose_name='نمایش در لیست')),
                ('order', models.IntegerField(default=10, verbose_name='ترتیب')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.producttype', verbose_name='محصول')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('purchase_price', models.BigIntegerField(verbose_name='قیمت خرید')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='سریال')),
                ('state', models.CharField(choices=[('IN_WAREHOUSE', 'در انبار'), ('SOLD', 'فروخته شده'), ('LOST', 'مفقود شده')], db_index=True, default='IN_WAREHOUSE', max_length=20, verbose_name='وضعیت')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.producttype', verbose_name='نوع محصول')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
