# Generated by Django 5.2 on 2026-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_attribute_brand_tag_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('code_name', models.SlugField(unique=True, verbose_name='نام کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections', verbose_name='تصویر')),
                ('seo_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان سئو')),
                ('seo_description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات سئو')),
                ('product_types', models.ManyToManyField(related_name='collections', to='product.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
