# Generated by Django 5.2 on 2026-08-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcollection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcollection',
            options={'verbose_name': 'کالکشن محصولات', 'verbose_name_plural': 'کالکشنهای محصولات'},
        ),
    ]
