# Generated by Django 5.2 on 2026-08-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcollection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('IN_WAREHOUSE', 'در انبار'), ('RESERVED', 'رزرو شده'), ('SOLD', 'فروخته شده'), ('LOST', 'مفقود شده')], db_index=True, default='IN_WAREHOUSE', max_length=20, verbose_name='وضعیت'),
        ),
    ]
