# Generated by Django 5.2 on 2026-08-28 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('event_type', models.CharField(choices=[('search', 'جستجو'), ('product_view', 'بازدید محصول'), ('category_view', 'بازدید دسته\u200cبندی')], db_index=True, max_length=32, verbose_name='نوع رویداد')),
                ('query', models.CharField(blank=True, max_length=255, verbose_name='عبارت جستجو')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='product.category', verbose_name='دسته\u200cبندی')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='product.producttype', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت کاتالوگ',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت کاتالوگ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='product_cat_event_t_5075b0_idx'), models.Index(fields=['product_type'], name='product_cat_product_b7f289_idx'), models.Index(fields=['category'], name='product_cat_categor_c10a4e_idx')],
            },
        ),
    ]
