server {
    listen 80;
    server_name k3isonfire.ir;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name k3isonfire.ir;

    ssl_certificate /etc/nginx/conf.d/server.crt;
    ssl_certificate_key /etc/nginx/conf.d/server.key;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        set $django_upstream http://django-web:8000;
        proxy_pass $django_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_cache off;
        proxy_no_cache 1;
        proxy_cache_bypass 1;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}
