# Generated by Django 5.2 on 2026-06-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=255, verbose_name='نام دستگاه')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('order', models.IntegerField(db_index=True, default=10, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'نوع دستگاه نصب',
                'verbose_name_plural': 'نوع دستگاه\u200cهای نصب',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=255, verbose_name='نام بازی')),
                ('size', models.PositiveIntegerField(verbose_name='حجم (گیگابایت)')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='installation.installationdevicetype')),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی\u200cها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InstallationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('total_price', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ کل')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت ادمین')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installation_requests', to='installation.installationdevicetype')),
                ('games', models.ManyToManyField(blank=True, related_name='installation_requests', to='installation.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست نصب',
                'verbose_name_plural': 'درخواست\u200cهای نصب',
                'ordering': ('-created_at',),
            },
        ),
    ]
