# Generated by Django 5.2 on 2026-06-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=1, upload_to='game-images', verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='game',
            name='device_type',
        ),
        migrations.AddField(
            model_name='game',
            name='device_type',
            field=models.ManyToManyField(blank=True, related_name='games', to='installation.installationdevicetype'),
        ),
        migrations.CreateModel(
            name='GameRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('source', models.CharField(choices=[('metacritic', 'Metacritic'), ('ign', 'IGN'), ('gamespot', 'GameSpot'), ('imdb', 'IMDb')], db_index=True, max_length=20, verbose_name='منبع')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='امتیاز')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='installation.game', verbose_name='بازی')),
            ],
            options={
                'verbose_name': 'امتیاز بازی',
                'verbose_name_plural': 'امتیازهای بازی',
                'unique_together': {('game', 'source')},
            },
        ),
    ]
