# Generated by Django 5.2 on 2026-06-30 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_game_image_remove_game_device_type_game_device_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationrequest',
            name='games',
        ),
        migrations.AddField(
            model_name='installationrequest',
            name='guest_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='installationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InstallationRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installation_items', to='installation.game')),
                ('installation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='installation.installationrequest')),
            ],
            options={
                'verbose_name': 'آیتم نصب',
                'verbose_name_plural': 'آیتم\u200cهای نصب',
                'unique_together': {('installation_request', 'game')},
            },
        ),
    ]
