# Generated by Django 5.2 on 2026-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_remove_installationrequest_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('done', 'انجام شده'), ('canceled', 'لغو شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت'),
        ),
    ]
