# Generated by Django 5.2 on 2026-07-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0004_installationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationrequest',
            name='tracking_code',
            field=models.PositiveIntegerField(default=1000, editable=False, unique=True, verbose_name='کد پیگیری'),
            preserve_default=False,
        ),
    ]
