# Generated by Django 5.2 on 2026-06-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_loginlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'verbose_name': '↧ لاگ ورود', 'verbose_name_plural': '↧ لاگ\u200cهای ورود'},
        ),
    ]
