# Generated by Django 5.2 on 2026-08-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0004_alter_productcollection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.producttype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product_type')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.CreateModel(
            name='OrderItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_products', to='product.product')),
            ],
            options={
                'verbose_name': 'کالای آیتم سفارش',
                'verbose_name_plural': 'کالاهای آیتم سفارش',
                'unique_together': {('order_item', 'product')},
            },
        ),
    ]
