# Generated by Django 5.2 on 2026-09-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_unique_together_orderitem_count_and_more'),
        ('user', '0005_city_unique_city_per_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_tehran_city_only', models.BooleanField(default=False, verbose_name='فقط شهر تهران')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='OrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('reservation_duration', models.PositiveIntegerField(default=30, help_text='مدت زمان رزرو کالا به دقیقه', verbose_name='مدت زمان رزرو')),
            ],
            options={
                'verbose_name': 'تنظیمات سفارش',
                'verbose_name_plural': 'تنظیمات سفارشات',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.BigIntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.deliverymethod'),
        ),
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('strategy', models.CharField(choices=[('fixed', 'ثابت'), ('by_weight', 'بر اساس وزن'), ('by_location', 'بر اساس موقعیت'), ('by_order_total', 'بر اساس مبلغ سفارش'), ('by_distance', 'بر اساس فاصله')], max_length=30, verbose_name='نوع محاسبه')),
                ('condition', models.JSONField(default=dict)),
                ('price', models.BigIntegerField()),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='order.deliverymethod')),
            ],
            options={
                'verbose_name': 'قیمت\u200cگذاری ارسال',
                'verbose_name_plural': 'قیمت\u200cگذاری\u200cهای ارسال',
            },
        ),
    ]
