# Generated by Django 5.2 on 2026-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_deliverymethod_orderconfig_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='زمان تحویل'),
        ),
    ]
