# Generated by Django 5.2 on 2026-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_paymentmethod_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfig',
            name='registration_enabled',
            field=models.BooleanField(default=True, help_text='با غیرفعال کردن این گزینه، کاربران امکان ثبت سفارش جدید نخواهند داشت.', verbose_name='امکان ثبت سفارش'),
        ),
    ]
