# Generated by Django 5.2 on 2026-10-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderconfig_registration_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created  at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra field')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('paid', 'پرداخت شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده')], max_length=20, verbose_name='وضعیت سفارش')),
                ('pattern_code', models.CharField(max_length=100, verbose_name='کد پترن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('tracking_code_param', models.CharField(blank=True, help_text='نام متغیر کد پیگیری در پترن مدیانا. خالی یعنی ارسال نشود. مثال: orderTracking', max_length=50, verbose_name='متغیر کد پیگیری')),
                ('full_name_param', models.CharField(blank=True, help_text='نام متغیر نام خریدار در پترن مدیانا. خالی یعنی ارسال نشود. مثال: fullName', max_length=50, verbose_name='متغیر نام خریدار')),
            ],
            options={
                'verbose_name': 'پیام وضعیت سفارش',
                'verbose_name_plural': 'پیام\u200cهای وضعیت سفارش',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('status',), name='unique_order_status_message')],
            },
        ),
    ]
