name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            set -e
            cd /backend
            git pull origin master
            # docker compose restart django-web
            # docker compose exec -T nginx nginx -s reload
            docker compose up -d --build
            docker compose ps
            echo "✅ Deployment completed!"
